# Generated by Django 5.1.6 on 2025-02-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_dashboard', '0003_hospital_alter_blooddonationappointment_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonationappointment',
            name='hospital',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
