# Generated by Django 5.1.6 on 2025-02-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_citizen_address_alter_citizen_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
