# Generated by Django 5.1.6 on 2025-02-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_citizen_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
